final class ScratchGroup {
  const ScratchGroup(this.id, this.title);
  final String id, title;
}

const scratchGroups = [ScratchGroup('cats', '猫猫百业')];

final class ScratchCollectible {
  const ScratchCollectible(
    this.index,
    this.job,
    this.name,
    this.story,
    this.clue,
    this.rarity, {
    required this.groupId,
    required this.artIndex,
    this.imageAsset = 'assets/scratch/cat-atlas.webp',
  });
  final int index;
  final String job, name, story, clue;
  final int rarity, artIndex;
  final String groupId, imageAsset;
}

const scratchRarities = ['普通', '稀有', '史诗', '传说'];
const scratchCollectibles = <ScratchCollectible>[
  ScratchCollectible(
    0,
    "面包师",
    "小麦",
    "把早安揉进面团，把温柔烤成面包。",
    "清晨五点，整条街就闻到了香气。",
    0,
    groupId: 'cats',
    artIndex: 0,
  ),
  ScratchCollectible(
    1,
    "邮递员",
    "信仔",
    "每一封信，都值得翻山越岭。",
    "包里装着远方，也装着想念。",
    0,
    groupId: 'cats',
    artIndex: 1,
  ),
  ScratchCollectible(
    2,
    "园丁",
    "苔苔",
    "种下的每一颗种子，都有自己的春天。",
    "爪子上总沾着一点泥土。",
    0,
    groupId: 'cats',
    artIndex: 2,
  ),
  ScratchCollectible(
    3,
    "学生",
    "豆包",
    "今天的难题，是午睡还是先写作业。",
    "书包里藏着一条小鱼干。",
    0,
    groupId: 'cats',
    artIndex: 3,
  ),
  ScratchCollectible(
    4,
    "咖啡师",
    "摩卡",
    "一杯温热的拿铁，刚好装下整个下午。",
    "最拿手的是猫爪拉花。",
    0,
    groupId: 'cats',
    artIndex: 4,
  ),
  ScratchCollectible(
    5,
    "农夫",
    "南瓜",
    "认真种菜，也认真在草帽下打盹。",
    "口袋里的种子比零食还多。",
    0,
    groupId: 'cats',
    artIndex: 5,
  ),
  ScratchCollectible(
    6,
    "护士",
    "棉棉",
    "贴上小小创可贴，再送你一个拥抱。",
    "随身小包里总有治愈的东西。",
    0,
    groupId: 'cats',
    artIndex: 6,
  ),
  ScratchCollectible(
    7,
    "花艺师",
    "山茶",
    "不擅长说的话，就交给花束吧。",
    "能把普通的一天扎成一束花。",
    0,
    groupId: 'cats',
    artIndex: 7,
  ),
  ScratchCollectible(
    8,
    "渔夫",
    "阿汐",
    "等鱼上钩，也等落日把海面染红。",
    "最有耐心，也最容易嘴馋。",
    0,
    groupId: 'cats',
    artIndex: 8,
  ),
  ScratchCollectible(
    9,
    "木匠",
    "木木",
    "用一双巧爪，给小动物们造个家。",
    "沙沙声里，一块木头有了新模样。",
    0,
    groupId: 'cats',
    artIndex: 9,
  ),
  ScratchCollectible(
    10,
    "画家",
    "点点",
    "胡须沾着颜料，眼睛盛着彩虹。",
    "把看见的世界变成七种颜色。",
    0,
    groupId: 'cats',
    artIndex: 10,
  ),
  ScratchCollectible(
    11,
    "图书管理员",
    "书卷",
    "每一本合上的书，都藏着一个宇宙。",
    "喜欢安静，也喜欢冒险故事。",
    0,
    groupId: 'cats',
    artIndex: 11,
  ),
  ScratchCollectible(
    12,
    "侦探",
    "福喵",
    "失踪的小鱼干，逃不过这双眼睛。",
    "一副放大镜，一百个为什么。",
    1,
    groupId: 'cats',
    artIndex: 12,
  ),
  ScratchCollectible(
    13,
    "魔术师",
    "墨墨",
    "帽子里没有兔子，只有惊喜和猫毛。",
    "眨一下眼，纸牌就不见了。",
    1,
    groupId: 'cats',
    artIndex: 13,
  ),
  ScratchCollectible(
    14,
    "船长",
    "罗盘",
    "风往哪里吹，故事就从哪里开始。",
    "望远镜的另一端，是新的海岸。",
    1,
    groupId: 'cats',
    artIndex: 14,
  ),
  ScratchCollectible(
    15,
    "摇滚乐手",
    "闪电",
    "世界太安静？那就拨响第一根弦。",
    "一到舞台上，就忘记了害羞。",
    1,
    groupId: 'cats',
    artIndex: 15,
  ),
  ScratchCollectible(
    16,
    "宇航员",
    "团子",
    "在失重的宇宙里，追一颗漂浮的鱼干。",
    "头盔外的星星格外清楚。",
    1,
    groupId: 'cats',
    artIndex: 16,
  ),
  ScratchCollectible(
    17,
    "摄影师",
    "快门",
    "把稍纵即逝的快乐，留在一张照片里。",
    "常说的一句话是：看这里！",
    1,
    groupId: 'cats',
    artIndex: 17,
  ),
  ScratchCollectible(
    18,
    "甜点师",
    "莓莓",
    "在蛋糕尖上，放一颗刚刚好的草莓。",
    "每次出场，都带着甜甜的香气。",
    1,
    groupId: 'cats',
    artIndex: 18,
  ),
  ScratchCollectible(
    19,
    "炼金术师",
    "琥珀",
    "今天的新配方：三滴月光，一点勇气。",
    "玻璃瓶里，冒着不认识的星光。",
    2,
    groupId: 'cats',
    artIndex: 19,
  ),
  ScratchCollectible(
    20,
    "星际领航员",
    "北辰",
    "即使迷失在银河，也认得回家的方向。",
    "摊开的地图上，没有一条普通的路。",
    2,
    groupId: 'cats',
    artIndex: 20,
  ),
  ScratchCollectible(
    21,
    "御厨",
    "金栗",
    "山珍海味之外，最想做一碗家常面。",
    "金线围裙下，是最挑剔的味蕾。",
    2,
    groupId: 'cats',
    artIndex: 21,
  ),
  ScratchCollectible(
    22,
    "梦境画家",
    "眠眠",
    "等你睡着，就来给你的梦添一抹颜色。",
    "画笔只在月亮升起以后发光。",
    2,
    groupId: 'cats',
    artIndex: 22,
  ),
  ScratchCollectible(
    23,
    "星愿收藏家",
    "星弥",
    "把每个小小的愿望收好，等它长成星星。",
    "斗篷里的每一颗星，都是谁的心愿。",
    3,
    groupId: 'cats',
    artIndex: 23,
  ),
];
