final class ScratchGroup {
  const ScratchGroup(this.id, this.title);
  final String id, title;
}

const scratchGroups = [
  ScratchGroup('cats', '猫猫百业'),
  ScratchGroup('dogs', '狗狗百业'),
];

// Published catalog sizes; entries are append-only to preserve saved indices.
const scratchLegacyCatalogSize = 24;
const scratchDogArtRows = [0, 304, 586, 862, 1132, 1354, 1536];

final class ScratchCollectible {
  const ScratchCollectible(
    this.index,
    this.job,
    this.name,
    this.story,
    this.clue,
    this.rarity, {
    required this.groupId,
    required this.artIndex,
    this.imageAsset = 'assets/scratch/cat-atlas.webp',
    this.artRows = const [0, 304, 576, 838, 1096, 1319, 1536],
  });
  final int index;
  final List<int> artRows;
  final String job, name, story, clue;
  final int rarity, artIndex;
  final String groupId, imageAsset;
}

const scratchRarities = ['普通', '稀有', '史诗', '传说'];
const scratchCollectibles = <ScratchCollectible>[
  ScratchCollectible(
    0,
    "面包师",
    "小麦",
    "清晨五点，小麦把第一炉面包摆在窗边。它总会多烤一根小法棍，留给收摊晚的邻居；等客人散去，才发现自己的胡须上还挂着面粉。",
    "清晨五点，整条街就闻到了香气。",
    0,
    groupId: 'cats',
    artIndex: 0,
  ),
  ScratchCollectible(
    1,
    "邮递员",
    "信仔",
    "信仔的邮包里，信封都按路程排得整整齐齐。只有写给山顶老猫的那封总放最上面，因为它想趁茶还热时，坐下来听对方念完。",
    "邮包里装着远方来信，也装着沉甸甸的想念。",
    0,
    groupId: 'cats',
    artIndex: 1,
  ),
  ScratchCollectible(
    2,
    "园丁",
    "苔苔",
    "苔苔从不催刚种下的种子。每天浇完水，它便蹲在花盆旁记下一点变化，连第一片歪歪的小叶子，都在本子上得了一个大大的圈。",
    "浇完水后，小爪子上总沾着一点湿泥土。",
    0,
    groupId: 'cats',
    artIndex: 2,
  ),
  ScratchCollectible(
    3,
    "学生",
    "豆包",
    "豆包决定写完三道题再午睡，却趴在第二题上打起呼噜。醒来时，书包里的小鱼干还在，它赶紧补完最后一道，才郑重地拆开点心。",
    "鼓鼓的书包里，悄悄藏着一条小鱼干。",
    0,
    groupId: 'cats',
    artIndex: 3,
  ),
  ScratchCollectible(
    4,
    "咖啡师",
    "摩卡",
    "摩卡练猫爪拉花时，第一朵总有六个脚趾。它把那杯留给自己，再端出一杯漂亮的五瓣奶泡；常客都说，窗边的下午从这一杯开始。",
    "端出的每杯拿铁上，都有拿手的猫爪拉花。",
    0,
    groupId: 'cats',
    artIndex: 4,
  ),
  ScratchCollectible(
    5,
    "农夫",
    "南瓜",
    "南瓜把种子装进背带裤的不同口袋，播种时一摸就知道是哪一种。午后它躲进草帽的阴影里打盹，醒来先数胡萝卜，再找忘在田边的午饭。",
    "背带裤口袋里的种子，常常比零食还多。",
    0,
    groupId: 'cats',
    artIndex: 5,
  ),
  ScratchCollectible(
    6,
    "护士",
    "棉棉",
    "棉棉给小病人贴好创可贴，还会在边角画一张笑脸。轮到自己拆开药箱时，里面常常多出折歪的纸花，它把每一朵都夹进值班本。",
    "随身小包里总有治愈的东西。",
    0,
    groupId: 'cats',
    artIndex: 6,
  ),
  ScratchCollectible(
    7,
    "花艺师",
    "山茶",
    "山茶替客人扎好花束，总要留下片朝外的小叶子。那是它不太会说出口的问候；等客人走远，它才对着空花瓶悄悄练习下一句祝福。",
    "能把普通的一天扎成一束花。",
    0,
    groupId: 'cats',
    artIndex: 7,
  ),
  ScratchCollectible(
    8,
    "渔夫",
    "阿汐",
    "阿汐戴着黄帽子等了整个下午，小桶里才多一条鱼。它忍着嘴馋，又坐了一会儿：今天的落日快把水面染成橘子色了，可不能错过。",
    "等鱼时最有耐心，闻到鱼香却最容易嘴馋。",
    0,
    groupId: 'cats',
    artIndex: 8,
  ),
  ScratchCollectible(
    9,
    "木匠",
    "木木",
    "木木做鸟屋时，会把门口再磨一遍，免得刮疼细细的翅膀。装好屋顶后，它把剩下的小木片拼成凳子，自己坐在树下等第一位房客。",
    "沙沙声里，一块木头有了新模样。",
    0,
    groupId: 'cats',
    artIndex: 9,
  ),
  ScratchCollectible(
    10,
    "画家",
    "点点",
    "点点画彩虹，总把最喜欢的黄色留到最后。今天一转头，湿漉漉的胡须扫过画纸，多出一朵奇怪的小云；它想了想，给云添上了笑脸。",
    "把看见的世界变成七种颜色。",
    0,
    groupId: 'cats',
    artIndex: 10,
  ),
  ScratchCollectible(
    11,
    "图书管理员",
    "书卷",
    "书卷白天轻声提醒大家翻书要慢，晚上却会为冒险故事屏住呼吸。每读到惊险处，它便推一下圆眼镜，确认桌边的热茶还稳稳放着。",
    "圆眼镜后喜欢安静的它，也爱读惊险的冒险故事。",
    0,
    groupId: 'cats',
    artIndex: 11,
  ),
  ScratchCollectible(
    12,
    "侦探",
    "福喵",
    "福喵接到小鱼干失踪的委托，把放大镜贴近空罐，发现盖子边缘没有新的爪印。它没有去追窗外路过的猫，而是请委托人重新演示昨天怎样收拾厨房。\n\n"
        "围裙一翻，半包鱼干从口袋里落了出来。委托人红着脸说，原来是自己怕受潮收起来了。福喵递回鱼干，在笔记旁画了个罐子：下次先查查自己的好主意。",
    "举起一副放大镜，脑袋里便有一百个为什么。",
    1,
    groupId: 'cats',
    artIndex: 12,
  ),
  ScratchCollectible(
    13,
    "魔术师",
    "墨墨",
    "墨墨第一次到图书馆表演，才知道观众都被提醒不能大声说话。它准备好的响亮咒语派不上用场，便把礼帽放低，让纸牌一张张从帽沿探出头。\n\n"
        "小猫们跟着手势屏住呼吸，最后一张牌翻过来，竟是管理员借出的书签。全场没有欢呼，只有一排拼命摇晃的尾巴。墨墨鞠躬时想，原来安静也能装下这么大的惊喜。",
    "盯着帽沿眨一下眼，手边的纸牌就不见了。",
    1,
    groupId: 'cats',
    artIndex: 13,
  ),
  ScratchCollectible(
    14,
    "船长",
    "罗盘",
    "罗盘航海时发现一片没画在地图上的礁岸，原本想赶在日落前靠近，把新发现记在自己的名字下面。望远镜里，浪花却总在同一个地方突然消失。\n\n"
        "它收起炫耀的念头，下令减速，沿外侧仔细标出暗礁。第二天再来时，船员们安全找到了一处浅湾。罗盘在地图边写下的第一个词，是可以慢慢抵达。",
    "望远镜的另一端，是新的海岸。",
    1,
    groupId: 'cats',
    artIndex: 14,
  ),
  ScratchCollectible(
    15,
    "摇滚乐手",
    "闪电",
    "闪电平时在乐器店试音，连声音开大一点都要先看看四周。音乐节那天，主唱忽然忘了开场词，台下也跟着安静下来，它紧张得把拨片攥出了汗。\n\n"
        "可熟悉的和弦一响，闪电便想起大家排练时笑着打拍子的样子。它先弹了一小段，让伙伴一个个接上。演出结束后，它又躲回音箱旁，却偷偷把下次报名表装进了琴包。",
    "抱起吉他一到舞台上，就忘记了平时的害羞。",
    1,
    groupId: 'cats',
    artIndex: 15,
  ),
  ScratchCollectible(
    16,
    "宇航员",
    "团子",
    "团子在空间舱里打开午餐，一块小鱼干从爪边飘走，正朝实验台慢慢翻跟头。它差点扑过去，想起培训时的话，又赶紧抓住身旁扶手。\n\n"
        "团子拿空餐袋兜住鱼干，再把每只盒子的搭扣逐一按紧。晚间通话时，它给地面的朋友看窗外的星星，也认真展示自己的新发明：一根把午餐拴在桌边的小绳子。",
    "透过圆圆的头盔，远处的星星看起来格外清楚。",
    1,
    groupId: 'cats',
    artIndex: 16,
  ),
  ScratchCollectible(
    17,
    "摄影师",
    "快门",
    "快门受邀拍全家照，最小的孩子却一见镜头就躲到椅子后面。它试着说了几次看这里，孩子反而把脸藏得更深，于是它先把相机放到了腿上。\n\n"
        "等家人开始讲午饭时打翻汤碗的趣事，椅子后终于传来笑声。快门没有再喊口令，只轻轻按下按钮。照片里没人站得整齐，可每一双眼睛都看着自己喜欢的人。",
    "举起相机时最常说的一句话是：看这里！",
    1,
    groupId: 'cats',
    artIndex: 17,
  ),
  ScratchCollectible(
    18,
    "甜点师",
    "莓莓",
    "莓莓为小店周年庆准备了高高的草莓蛋糕，摆好时才发现最后一颗草莓长得歪，怎么放都不对称。它想换一颗，送水果的老奶奶却说，那是今年最后一筐了。\n\n"
        "莓莓把小草莓切成两片，拼成一对靠在一起的耳朵，又用奶油点上胡须。客人们围着蛋糕笑起来，它也终于松开眉头：刚刚好，原来不一定是圆圆正正。",
    "每次出场，都带着甜甜的香气。",
    1,
    groupId: 'cats',
    artIndex: 18,
  ),
  ScratchCollectible(
    19,
    "炼金术师",
    "琥珀",
    "琥珀学炼金时，最拿手的是把药水调得漂亮，最不擅长的却是承认配方出了错。它曾调出一瓶会亮整夜的星光，第二天，借来做实验的花却垂下了叶子。\n\n"
        "后来它找到一种只亮片刻的配方，原料是三滴月光和几粒干净的矿砂。庆典前，大家想要更耀眼的长明灯，它犹豫许久，还是把两瓶药水并排摆好，说明各自的缺点。伙伴们选择轮流点亮小瓶，让花圃在间隙里好好休息。\n\n"
        "琥珀把这一页命名为三滴月光，一点勇气。如今每次开工，它都会先摸摸窗边新叶，再洗净量杯。那点勇气，是愿意让别人看见还不完美的答案。",
    "玻璃瓶里，冒着不认识的星光。",
    2,
    groupId: 'cats',
    artIndex: 19,
  ),
  ScratchCollectible(
    20,
    "星际领航员",
    "北辰",
    "北辰年轻时背得出每一条星路，却曾在一场尘云里找不到熟悉的星座。返航之后，它没有把那次绕路擦掉，而是在地图上留了一小块空白，提醒自己还有看不清的地方。\n\n"
        "多年后，一艘货船请求它带队穿过新航道，能比原路省下一夜。北辰看着漂亮的计算结果，又看了看船上第一次远行的学员，选择绕行，并把自己当年的记录摊在大家面前。航程长了一些，学员却学会了交叉核对航标，也第一次亲手找到了家乡的光点。\n\n"
        "北辰的望远镜仍朝向未知处，桌上则一直放着旧地图。每次平安靠岸，它先给家里报个信，再慢慢修补那些已经磨毛的折角。",
    "摊开的地图上，没有一条普通的路。",
    2,
    groupId: 'cats',
    artIndex: 20,
  ),
  ScratchCollectible(
    21,
    "御厨",
    "金栗",
    "金栗第一次进宫做学徒时，只带了一张家里留下的面方。师傅让它练最细的刀工、认最难分辨的香料，它把面方夹进食谱深处，好几年都没再翻开。\n\n"
        "一次宫宴结束，洗碗的老伙计说自己忙得没赶上晚饭。桌上还摆着精致的点心，金栗却想起老伙计不爱吃甜，便解开金线围裙上的装饰，重新烧了一锅水。它把面煮得柔软，浇上清汤，又叫回还在收拾的帮厨，一人盛了一碗。\n\n"
        "第二天，御厨的食谱第一页换成了那张旧面方。金栗仍会认真试每一道宫宴菜，只是再忙也要先问厨房里的伙伴：你们今天吃过了吗。",
    "金线围裙下，是最挑剔的味蕾。",
    2,
    groupId: 'cats',
    artIndex: 21,
  ),
  ScratchCollectible(
    22,
    "梦境画家",
    "眠眠",
    "眠眠的画笔只在月亮升起后发光。刚学会进入梦境时，它总替别人画最明亮的天空，直到一个小画家醒来抱怨：梦里的雨没了，可自己本来想练习画水洼。\n\n"
        "那晚眠眠收起整盒金色颜料，重新走进那个灰蒙蒙的梦。它没有赶走乌云，只问小画家想把第一笔落在哪里。两只猫蹲在梦中的街角，给水洼添上窗灯的倒影，再留出一块没有上色的地方，让梦的主人自己完成。\n\n"
        "后来，眠眠的画架边多了一张空白小纸条。每次出门，它都先想一想该问什么，而不是该画什么。等最后一扇窗暗下来，它才回家洗笔，悄悄为自己的午睡留一点浅蓝。",
    "画笔只在月亮升起以后发光。",
    2,
    groupId: 'cats',
    artIndex: 22,
  ),
  ScratchCollectible(
    23,
    "星愿收藏家",
    "星弥",
    "星弥收藏的第一颗星，还没有指甲大。那时它替街坊整理旧物，从一只裂口的玻璃瓶里找到一张纸条，上面写着想把小提琴练到能完整拉完一首曲子。它把纸条放在窗边，每晚都能听见隔壁断断续续的练习声。\n\n"
        "后来那声音停了，纸条上的微光也暗下来。星弥本想把瓶子封好，留住最后一点亮光，却发现窗外的人抱着琴盒，正准备把琴送走。它追下楼，没有许诺能让谁立刻学会，只请对方再拉一次，自己愿意从第一个走调的音听起。\n\n"
        "往后的许多个傍晚，星弥都带着玻璃瓶去做听众。曲子终于连贯起来那天，纸条缓缓蜷成一颗小星，落进瓶底。它这才知道，愿望要由许多真实的小步养大；收藏家能做的，是记住有人正在努力，别让那一点光无人看见。\n\n"
        "如今，星弥把收来的星缝在深蓝斗篷内侧，每颗都记着主人的名字。裂口的瓶子始终挂在最顺手的位置，用来装尚未长成的心愿。有人问哪颗最珍贵，它便托起那颗小小的琴星，等它亮一亮，再轻轻盖上瓶口。",
    "斗篷里的每一颗星，都是谁的心愿。",
    3,
    groupId: 'cats',
    artIndex: 23,
  ),
  ScratchCollectible(
    24,
    '消防员',
    '火苗',
    "火苗每次出勤前，都要把红头盔扶正两遍。今天救下树上的小鸟后，它又爬了一趟梯子，把落在枝头的小围巾也取了回来。",
    '红头盔下，藏着一颗勇敢的心。',
    0,
    groupId: 'dogs',
    artIndex: 0,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    25,
    '快递员',
    '包包',
    "包包抱着纸箱上楼时，总要先用鼻尖确认门牌。今天收件人不在家，它把包裹放进约好的避雨柜，再画一只小爪印，告诉对方自己来过。",
    '无论大小，每一个纸箱都要稳稳抱好。',
    0,
    groupId: 'dogs',
    artIndex: 1,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    26,
    '园丁',
    '麦穗',
    "麦穗清早拎水壶巡花园，发现蝴蝶停在刚要浇水的花上。它便绕去另一边，等翅膀晒干飞远，才把壶嘴压低，慢慢浇湿花根旁的土。",
    '清早出门时，洒水壶里已装好收集的露水。',
    0,
    groupId: 'dogs',
    artIndex: 2,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    27,
    '学生',
    '饭团',
    "饭团的绿书包里装着课本，也装着一路捡来的为什么。今天它举手问蚂蚁上不上学，老师让它下课去观察；它连回家路上都舍不得收起本子。",
    '清脆的下课铃一响，尾巴就忍不住开始摇。',
    0,
    groupId: 'dogs',
    artIndex: 3,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    28,
    '美容师',
    '泡芙',
    "泡芙给怕梳毛的小狗剪下一撮打结的毛，先让它闻闻梳子。等客人放松下来，它的粉围裙已经沾满毛球，却还认真给镜子旁别上蝴蝶结。",
    '粉色围裙上，总粘着几朵小毛球。',
    0,
    groupId: 'dogs',
    artIndex: 4,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    29,
    '牧羊人',
    '云朵',
    "云朵每天收队都要数两遍羊，第二遍总故意放慢。最小的那只喜欢落在后面看花，听见熟悉的口哨，便一路小跑，蹭到弯弯的牧杖旁。",
    '一声口哨，山坡上的白云就回家了。',
    0,
    groupId: 'dogs',
    artIndex: 5,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    30,
    '雪山救援员',
    '暖暖',
    "暖暖出门前会把红背包的肩带拉紧，再摸一摸保温毯。今天找到迷路的登山客，它先送上温水，等对方不再发抖，才领着大家慢慢下山。",
    '红色背包里，总备着一份温暖。',
    0,
    groupId: 'dogs',
    artIndex: 6,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    31,
    '花艺师',
    '铃兰',
    "铃兰给新开的小店送花，发现门口没有合适的花瓶。它便把长耳朵往后一拢，借来一个旧水壶，让几朵路边小花也能站得精神又漂亮。",
    '垂下的长长耳朵边，常常别着一朵小花。',
    0,
    groupId: 'dogs',
    artIndex: 7,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    32,
    '雪地邮差',
    '雪饼',
    "雪饼走过厚雪时，总把信封藏在冬衣内侧。到了门前，它先跺净靴子上的雪，再轻轻敲门，免得那句远方的问候还没拆开就被雪水打湿。",
    '信封很轻，想念却值得走很远。',
    0,
    groupId: 'dogs',
    artIndex: 8,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    33,
    '修理师',
    '螺帽',
    "螺帽修好一辆吱呀响的玩具车，没有急着合上工具箱。它趴在地上陪小主人试跑，听了三圈，才把那颗总会松动的螺丝再拧紧半圈。",
    '旧工具箱一打开，吱呀响的烦恼就有办法了。',
    0,
    groupId: 'dogs',
    artIndex: 9,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    34,
    '画家',
    '斑斑',
    "斑斑替花坛画招牌，不小心甩出几滴颜色。它看看自己身上的斑点，干脆把墨点添成瓢虫；花还没开，招牌就已经引来一圈蹲着数虫的孩子。",
    '调色盘上，从来不缺明亮的颜色。',
    0,
    groupId: 'dogs',
    artIndex: 10,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    35,
    '图书管理员',
    '卷卷',
    "卷卷把退回来的书放好，会顺手记住读者最喜欢的那一页。下次圆眼镜后看见熟悉的面孔，它就从架上抽出另一本，问要不要接着去冒险。",
    '圆眼镜后面，藏着整座书架的秘密。',
    0,
    groupId: 'dogs',
    artIndex: 11,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    36,
    '侦探',
    '雷达',
    "面包店低处的备货篮里接连少了三只牛角包，雷达循着碎屑找到了后院，却只看见一串小得出奇的脚印。它没有急着宣布破案，而是在墙边放下半只面包，蹲着等到天黑。\n\n"
        "原来，新搬来的小刺猬够不着柜台，也不好意思开口。第二天，店门口多了一张矮凳。雷达合上笔记本，只写了一句：有些谜底，需要先听听肚子的声音。",
    '放大镜之外，还有一双竖起的耳朵。',
    1,
    groupId: 'dogs',
    artIndex: 12,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    37,
    '魔术师',
    '蝶蝶',
    "蝶蝶的紫礼帽在演出前被风吹进了水桶，帽里的纸牌全皱了。它正想取消节目，一个等在门边的孩子却说，自己从没看过会游泳的纸牌。\n\n"
        "蝶蝶笑了起来，把纸牌折成小船，借魔杖轻轻推着它们绕水盆转圈，最后从袖口抽出一朵干燥的纸花。谢幕时帽子还在滴水，观众却排着队，想学那只最不会沉的小船。",
    '凑近紫色礼帽，能听见轻轻的沙沙声。',
    1,
    groupId: 'dogs',
    artIndex: 13,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    38,
    '船长',
    '海盐',
    "海盐接到一张远岛送货单，船上的新厨师担心自己晕船，偷偷想留在岸上。海盐没有说忍一忍就好，而是把航线摊开，和大家找能分段停靠的港口。\n\n"
        "一路上，船员轮流陪厨师到甲板透气，它则用望远镜提前寻找平稳的水面。到岛那天，午饭终于是热的。海盐在航海日志里写下，今天船上的每一位伙伴都到了。",
    '举起望远镜时，眼里总有下一座想去的小岛。',
    1,
    groupId: 'dogs',
    artIndex: 14,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    39,
    '爵士乐手',
    '蓝调',
    "蓝调习惯在小酒馆吹萨克斯，最近却总有邻居说它练习得太晚。它抱着乐器去敲门，才知道隔壁住着一位需要早睡的老人，最想念的却是从前常听的舞曲。\n\n"
        "蓝调把练习挪到傍晚，特意慢慢学会那段旧旋律。窗帘后第一次传来轻轻的打拍声时，它没有再加大音量，只把最后一个音吹得长一点，让对方从容跟上。",
    '第一段旋律响起，街灯也温柔了。',
    1,
    groupId: 'dogs',
    artIndex: 15,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    40,
    '宇航员',
    '雪球',
    "雪球踏上月面后的第一个爪印，比训练时预想的小。它兴奋地回头拍照，却看见同伴的取样袋被细尘卡住，正笨拙地用厚手套反复拉扯。\n\n"
        "雪球先收起相机，帮忙托稳袋口，再一起把标记贴好。回到舱内，它给那张只有半个爪印的照片写了注释：后半步留给伙伴。透明头盔里的笑容，倒是一点也没少拍进去。",
    '透明头盔里，笑容比星星还亮。',
    1,
    groupId: 'dogs',
    artIndex: 16,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    41,
    '探险家',
    '栗子',
    "栗子按地图寻找瀑布，走到终点却只见一条细细的溪流。它失望地咬开备用饼干，忽然发现岩石背面有整齐的水痕，树叶也挂在高处的缝里。\n\n"
        "它没有为了找到大瀑布继续往陡坡爬，而是取出指南针，标好位置和季节。几个月后雨水丰沛，栗子带着同伴沿安全的小路重来。原来有些发现，还需要给它一点时间。",
    '指南针旁边，还装着一块备用饼干。',
    1,
    groupId: 'dogs',
    artIndex: 17,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    42,
    '甜点师',
    '奶油',
    "奶油想做一只很高的庆生蛋糕，试了三次，上层都悄悄往旁边歪。它正准备第四次，寿星来取蛋糕，说今天会有几个个子特别小的朋友。\n\n"
        "奶油看看高高的托盘，改做了一圈小蛋糕，每只都放上一颗草莓。聚会时，大家不用伸长爪子等人分切，也能把自己那份端到喜欢的位置。它摇着尾巴，把新做法记在了食谱首页。",
    '每一块蛋糕，都经过尾巴的赞成。',
    1,
    groupId: 'dogs',
    artIndex: 18,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    43,
    '炼金术师',
    '墨晶',
    "墨晶小时候常把池边会发亮的石头带回家，一颗颗装进玻璃瓶。学会炼金后，它终于调出了能让矿砂发光的药水，却发现不同石头泡进去，亮起的时长完全不一样。\n\n"
        "为了做一盏读书灯，它连续几夜试新配方，桌上堆满标记失败的瓶子。朋友建议把最亮的一瓶先送去展览，墨晶却留下来，把那些失败瓶重新分组记录。原来几种微弱的光接续亮起，反而比一阵耀眼的闪光更适合陪人读完一页书。\n\n"
        "现在，它穿着深青长袍守在桌边，仍会为陌生的光色高兴得卷起耳朵。每晚洗完瓶子，它都留出半小时读闲书，确认自己的新发明真的让眼睛舒服一些。",
    '深夜的玻璃瓶里，有星光轻轻翻涌。',
    2,
    groupId: 'dogs',
    artIndex: 0,
    imageAsset: 'assets/scratch/dog-epic-atlas.webp',
    artRows: const [0, 512],
  ),
  ScratchCollectible(
    44,
    '极光巡守',
    '北风',
    "北风小时候，总把山顶的极光当作回家的路。有一年大雪封山，光带移到了山谷另一侧，它追着走了很久，直到一位老巡守提着灯找到它。那天北风才知道，好看的光，不一定会带人回家。\n\n"
        "接过巡守的提灯后，它在每个岔路口系上能摸到的绳结，自己却迟迟不敢独自走完北坡。一次送药途中，风雪掩住了脚印，身后的年轻邮差问它怕不怕。北风点点头，把灯举低了一些：怕，所以我们走慢一点，一起认路。\n\n"
        "现在，绿色的极光升起时，山下总能看见另一点缓缓移动的灯火。北风回到小屋，会先烘干同伴的手套，再给自己泡一杯热牛奶。",
    '提灯升起时，天空也披上绿色的绸带。',
    2,
    groupId: 'dogs',
    artIndex: 1,
    imageAsset: 'assets/scratch/dog-epic-atlas.webp',
    artRows: const [0, 512],
  ),
  ScratchCollectible(
    45,
    '御厨',
    '金豆',
    "金豆刚接手宫里的蒸笼时，能包出边缘完全一样的包子，却总算不准收工的人数。一次宴席结束，留给夜班守卫的那笼已经凉了，它才发现食谱里没有写等人回来的时间。\n\n"
        "下一次宫宴，它提前问清换班的时刻，把一小份面团留到最后。正要下锅，前厅又来催一道加菜，金豆便请帮厨接手蒸笼，自己把步骤和时间逐项交代。它第一次没有包办所有事，却让前厅和后厨都按时吃上了热饭。\n\n"
        "如今，金豆的金边衣袖总挽得高高的，食谱上也多了一栏同伴的名字。夜里最后一笼冒出白汽，它会先掰开一只看看松软程度，再坐下来听守卫讲今天门外的趣事。",
    '忙碌的金边衣袖旁，飘来一阵熟悉的家的味道。',
    2,
    groupId: 'dogs',
    artIndex: 2,
    imageAsset: 'assets/scratch/dog-epic-atlas.webp',
    artRows: const [0, 512],
  ),
  ScratchCollectible(
    46,
    '织梦师',
    '绮梦',
    "绮梦最早只会把银色丝线织成规则的网。月亮睡着后，丝线会映出远处的星光，可它织出的梦总太整齐，连风吹过树叶的声音都像在数拍子。\n\n"
        "有一晚，一个孩子请它留下梦里那座歪歪的桥，那是自己和家人用积木搭过的样子。绮梦试着松开几处绳结，不再把每根线拉到同样紧。桥没有散，反而能轻轻晃动，让梦里的两个人扶着彼此走过去。它明白了，安心并不总来自把一切安排妥当，也可以来自有人陪着。\n\n"
        "从那以后，绮梦的织网里总留着一点松弛。披着紫斗篷收工时，它会把剩下的短线编成杯垫，给床头那杯温水一个不必摆得笔直的位置。",
    '月亮睡着以后，银线才开始闪光。',
    2,
    groupId: 'dogs',
    artIndex: 3,
    imageAsset: 'assets/scratch/dog-epic-atlas.webp',
    artRows: const [0, 512],
  ),
  ScratchCollectible(
    47,
    '星愿守护者',
    '曜曜',
    "曜曜还没有王冠时，只负责在小镇广场收拾庆典后的纸星星。别人挑走金亮的，它却会把皱掉的也装进口袋。有一颗上面写着：希望明天，还有人愿意听我唱歌。字迹被雨水泡开了，它一直没找到写字的人。\n\n"
        "那年冬天，广场的许愿星忽然不再发光。大家以为是愿望不够大，写下更远的旅行、更高的城堡，星星却越来越暗。曜曜没有添上自己的纸条。它披着旧斗篷，挨家敲门，问每个人最近有什么想做、又没能做成的小事。它问得很慢，有时坐了半天，对方才肯说出第一句话。\n\n"
        "它替怕冷的花艺师修好窗缝，陪不敢登台的乐手在空广场练习，也找到那张纸星星的主人，认真听完了一首总在同一处唱错的歌。每完成一件小事，斗篷上就亮起一点光。曜曜这才明白，星星不能替谁实现愿望，它们只是提醒大家，别把彼此的话忘了。\n\n"
        "春天到来时，居民把那些重新发亮的纸星星编成王冠送给它。如今曜曜仍会在庆典后留下，弯腰捡起最后一颗皱纸星。它把王冠放在身旁，腾出两只爪子，轻轻将纸展开。无论上面写着什么，它都会从头读到最后。",
    '王冠上的星星，会回应你的心愿。',
    3,
    groupId: 'dogs',
    artIndex: 23,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
];
