final class ScratchGroup {
  const ScratchGroup(this.id, this.title);
  final String id, title;
}

const scratchGroups = [
  ScratchGroup('cats', '猫猫百业'),
  ScratchGroup('dogs', '狗狗百业'),
];

// Published catalog sizes; entries are append-only to preserve saved indices.
const scratchLegacyCatalogSize = 24;
const scratchDogArtRows = [0, 304, 586, 862, 1132, 1354, 1536];

final class ScratchCollectible {
  const ScratchCollectible(
    this.index,
    this.job,
    this.name,
    this.story,
    this.clue,
    this.rarity, {
    required this.groupId,
    required this.artIndex,
    this.imageAsset = 'assets/scratch/cat-atlas.webp',
    this.artRows = const [0, 304, 576, 838, 1096, 1319, 1536],
  });
  final int index;
  final List<int> artRows;
  final String job, name, story, clue;
  final int rarity, artIndex;
  final String groupId, imageAsset;
}

const scratchRarities = ['普通', '稀有', '史诗', '传说'];
const scratchCollectibles = <ScratchCollectible>[
  ScratchCollectible(
    0,
    "面包师",
    "小麦",
    "把早安揉进面团，把温柔烤成面包。",
    "清晨五点，整条街就闻到了香气。",
    0,
    groupId: 'cats',
    artIndex: 0,
  ),
  ScratchCollectible(
    1,
    "邮递员",
    "信仔",
    "每一封信，都值得翻山越岭。",
    "包里装着远方，也装着想念。",
    0,
    groupId: 'cats',
    artIndex: 1,
  ),
  ScratchCollectible(
    2,
    "园丁",
    "苔苔",
    "种下的每一颗种子，都有自己的春天。",
    "爪子上总沾着一点泥土。",
    0,
    groupId: 'cats',
    artIndex: 2,
  ),
  ScratchCollectible(
    3,
    "学生",
    "豆包",
    "今天的难题，是午睡还是先写作业。",
    "书包里藏着一条小鱼干。",
    0,
    groupId: 'cats',
    artIndex: 3,
  ),
  ScratchCollectible(
    4,
    "咖啡师",
    "摩卡",
    "一杯温热的拿铁，刚好装下整个下午。",
    "最拿手的是猫爪拉花。",
    0,
    groupId: 'cats',
    artIndex: 4,
  ),
  ScratchCollectible(
    5,
    "农夫",
    "南瓜",
    "认真种菜，也认真在草帽下打盹。",
    "口袋里的种子比零食还多。",
    0,
    groupId: 'cats',
    artIndex: 5,
  ),
  ScratchCollectible(
    6,
    "护士",
    "棉棉",
    "贴上小小创可贴，再送你一个拥抱。",
    "随身小包里总有治愈的东西。",
    0,
    groupId: 'cats',
    artIndex: 6,
  ),
  ScratchCollectible(
    7,
    "花艺师",
    "山茶",
    "不擅长说的话，就交给花束吧。",
    "能把普通的一天扎成一束花。",
    0,
    groupId: 'cats',
    artIndex: 7,
  ),
  ScratchCollectible(
    8,
    "渔夫",
    "阿汐",
    "等鱼上钩，也等落日把海面染红。",
    "最有耐心，也最容易嘴馋。",
    0,
    groupId: 'cats',
    artIndex: 8,
  ),
  ScratchCollectible(
    9,
    "木匠",
    "木木",
    "用一双巧爪，给小动物们造个家。",
    "沙沙声里，一块木头有了新模样。",
    0,
    groupId: 'cats',
    artIndex: 9,
  ),
  ScratchCollectible(
    10,
    "画家",
    "点点",
    "胡须沾着颜料，眼睛盛着彩虹。",
    "把看见的世界变成七种颜色。",
    0,
    groupId: 'cats',
    artIndex: 10,
  ),
  ScratchCollectible(
    11,
    "图书管理员",
    "书卷",
    "每一本合上的书，都藏着一个宇宙。",
    "喜欢安静，也喜欢冒险故事。",
    0,
    groupId: 'cats',
    artIndex: 11,
  ),
  ScratchCollectible(
    12,
    "侦探",
    "福喵",
    "失踪的小鱼干，逃不过这双眼睛。",
    "一副放大镜，一百个为什么。",
    1,
    groupId: 'cats',
    artIndex: 12,
  ),
  ScratchCollectible(
    13,
    "魔术师",
    "墨墨",
    "帽子里没有兔子，只有惊喜和猫毛。",
    "眨一下眼，纸牌就不见了。",
    1,
    groupId: 'cats',
    artIndex: 13,
  ),
  ScratchCollectible(
    14,
    "船长",
    "罗盘",
    "风往哪里吹，故事就从哪里开始。",
    "望远镜的另一端，是新的海岸。",
    1,
    groupId: 'cats',
    artIndex: 14,
  ),
  ScratchCollectible(
    15,
    "摇滚乐手",
    "闪电",
    "世界太安静？那就拨响第一根弦。",
    "一到舞台上，就忘记了害羞。",
    1,
    groupId: 'cats',
    artIndex: 15,
  ),
  ScratchCollectible(
    16,
    "宇航员",
    "团子",
    "在失重的宇宙里，追一颗漂浮的鱼干。",
    "头盔外的星星格外清楚。",
    1,
    groupId: 'cats',
    artIndex: 16,
  ),
  ScratchCollectible(
    17,
    "摄影师",
    "快门",
    "把稍纵即逝的快乐，留在一张照片里。",
    "常说的一句话是：看这里！",
    1,
    groupId: 'cats',
    artIndex: 17,
  ),
  ScratchCollectible(
    18,
    "甜点师",
    "莓莓",
    "在蛋糕尖上，放一颗刚刚好的草莓。",
    "每次出场，都带着甜甜的香气。",
    1,
    groupId: 'cats',
    artIndex: 18,
  ),
  ScratchCollectible(
    19,
    "炼金术师",
    "琥珀",
    "今天的新配方：三滴月光，一点勇气。",
    "玻璃瓶里，冒着不认识的星光。",
    2,
    groupId: 'cats',
    artIndex: 19,
  ),
  ScratchCollectible(
    20,
    "星际领航员",
    "北辰",
    "即使迷失在银河，也认得回家的方向。",
    "摊开的地图上，没有一条普通的路。",
    2,
    groupId: 'cats',
    artIndex: 20,
  ),
  ScratchCollectible(
    21,
    "御厨",
    "金栗",
    "山珍海味之外，最想做一碗家常面。",
    "金线围裙下，是最挑剔的味蕾。",
    2,
    groupId: 'cats',
    artIndex: 21,
  ),
  ScratchCollectible(
    22,
    "梦境画家",
    "眠眠",
    "等你睡着，就来给你的梦添一抹颜色。",
    "画笔只在月亮升起以后发光。",
    2,
    groupId: 'cats',
    artIndex: 22,
  ),
  ScratchCollectible(
    23,
    "星愿收藏家",
    "星弥",
    "把每个小小的愿望收好，等它长成星星。",
    "斗篷里的每一颗星，都是谁的心愿。",
    3,
    groupId: 'cats',
    artIndex: 23,
  ),
  ScratchCollectible(
    24,
    '消防员',
    '火苗',
    '听见呼救就出发，把平安带回每一个家。',
    '红头盔下，藏着一颗勇敢的心。',
    0,
    groupId: 'dogs',
    artIndex: 0,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    25,
    '快递员',
    '包包',
    '小短腿跑得飞快，今天的惊喜准时送达。',
    '每一个纸箱，都要稳稳抱好。',
    0,
    groupId: 'dogs',
    artIndex: 1,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    26,
    '园丁',
    '麦穗',
    '把花园照顾好，也给蝴蝶留个歇脚的地方。',
    '洒水壶里装着清晨的露水。',
    0,
    groupId: 'dogs',
    artIndex: 2,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    27,
    '学生',
    '饭团',
    '书包比自己还大，好奇心比书包还大。',
    '下课铃一响，尾巴就开始摇。',
    0,
    groupId: 'dogs',
    artIndex: 3,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    28,
    '美容师',
    '泡芙',
    '梳顺每一缕毛，也梳走一点小烦恼。',
    '粉色围裙上，总粘着几朵小毛球。',
    0,
    groupId: 'dogs',
    artIndex: 4,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    29,
    '牧羊人',
    '云朵',
    '数清每一只小羊，再陪它们看晚霞。',
    '一声口哨，山坡上的白云就回家了。',
    0,
    groupId: 'dogs',
    artIndex: 5,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    30,
    '雪山救援员',
    '暖暖',
    '风雪再大，也会循着你的声音找到你。',
    '红色背包里，总备着一份温暖。',
    0,
    groupId: 'dogs',
    artIndex: 6,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    31,
    '花艺师',
    '铃兰',
    '把路边的小花，扎成值得纪念的一天。',
    '长长的耳朵边，别着一朵花。',
    0,
    groupId: 'dogs',
    artIndex: 7,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    32,
    '雪地邮差',
    '雪饼',
    '踩着厚厚的雪，把远方的问候送到门前。',
    '信封很轻，想念却值得走很远。',
    0,
    groupId: 'dogs',
    artIndex: 8,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    33,
    '修理师',
    '螺帽',
    '拧紧一颗螺丝，让旧玩具重新转起来。',
    '工具箱一打开，就有办法了。',
    0,
    groupId: 'dogs',
    artIndex: 9,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    34,
    '画家',
    '斑斑',
    '身上的斑点是天生的，画里的颜色是快乐的。',
    '调色盘上，从来不缺明亮的颜色。',
    0,
    groupId: 'dogs',
    artIndex: 10,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    35,
    '图书管理员',
    '卷卷',
    '替每一位读者，找到刚刚好的故事。',
    '圆眼镜后面，藏着整座书架的秘密。',
    0,
    groupId: 'dogs',
    artIndex: 11,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    36,
    '侦探',
    '雷达',
    '再小的线索，也逃不过敏锐的鼻尖。',
    '放大镜之外，还有一双竖起的耳朵。',
    1,
    groupId: 'dogs',
    artIndex: 12,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    37,
    '魔术师',
    '蝶蝶',
    '挥一下魔杖，把平凡变成一声惊叹。',
    '礼帽里传来轻轻的沙沙声。',
    1,
    groupId: 'dogs',
    artIndex: 13,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    38,
    '船长',
    '海盐',
    '只要伙伴都在，哪里都是值得抵达的港湾。',
    '望远镜里，总有下一座小岛。',
    1,
    groupId: 'dogs',
    artIndex: 14,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    39,
    '爵士乐手',
    '蓝调',
    '把夜晚吹得柔软，让每条尾巴跟着摇摆。',
    '第一段旋律响起，街灯也温柔了。',
    1,
    groupId: 'dogs',
    artIndex: 15,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    40,
    '宇航员',
    '雪球',
    '第一次登上月球，先留下一个小小爪印。',
    '透明头盔里，笑容比星星还亮。',
    1,
    groupId: 'dogs',
    artIndex: 16,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    41,
    '探险家',
    '栗子',
    '沿着未知的小径，发现地图之外的惊喜。',
    '指南针旁边，还装着一块备用饼干。',
    1,
    groupId: 'dogs',
    artIndex: 17,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    42,
    '甜点师',
    '奶油',
    '把快乐一层层叠好，再点缀一颗草莓。',
    '每一块蛋糕，都经过尾巴的赞成。',
    1,
    groupId: 'dogs',
    artIndex: 18,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    43,
    '炼金术师',
    '墨晶',
    '把一点好奇心，熬成会发光的新配方。',
    '深夜的玻璃瓶里，有星光轻轻翻涌。',
    2,
    groupId: 'dogs',
    artIndex: 19,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    44,
    '极光巡守',
    '北风',
    '守着漫长的冬夜，为迷路的人点亮极光。',
    '提灯升起时，天空也披上绿色的绸带。',
    2,
    groupId: 'dogs',
    artIndex: 20,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    45,
    '御厨',
    '金豆',
    '宫宴再隆重，也记得给伙伴留一笼热包子。',
    '金边衣袖里，藏着家的味道。',
    2,
    groupId: 'dogs',
    artIndex: 21,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    46,
    '织梦师',
    '绮梦',
    '把散落的星光，织成一场安心的好梦。',
    '月亮睡着以后，银线才开始闪光。',
    2,
    groupId: 'dogs',
    artIndex: 22,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
  ScratchCollectible(
    47,
    '星愿守护者',
    '曜曜',
    '守护每一个真诚的愿望，直到它照亮自己的天空。',
    '王冠上的星星，会回应你的心愿。',
    3,
    groupId: 'dogs',
    artIndex: 23,
    imageAsset: 'assets/scratch/dog-atlas.webp',
    artRows: scratchDogArtRows,
  ),
];
