#!/usr/bin/env python3
"""Generate the offline verse constants from the reviewed provenance catalog."""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/design/cat-scratch/poetry-library.json'
TARGET = ROOT / 'app/lib/features/scratch/blank_card_poems.dart'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--verbose', action='store_true')
    args = parser.parse_args()
    try:
        entries = json.loads(SOURCE.read_text(encoding='utf-8'))['entries']
        texts = [entry['text'] for entry in entries]
        keys = [re.sub(r'[^\u4e00-\u9fff]', '', text) for text in texts]
        if len(texts) != 2000 or len(set(keys)) != 2000:
            raise ValueError('expected exactly 2000 distinct couplets')
        pattern = re.compile(r'([\u4e00-\u9fff]{5}|[\u4e00-\u9fff]{7})，\n([\u4e00-\u9fff]{5}|[\u4e00-\u9fff]{7})[。！？]')
        for index, text in enumerate(texts):
            match = pattern.fullmatch(text)
            if not match or len(match[1]) != len(match[2]):
                raise ValueError(f'invalid couplet at index {index}')
        content = ('// Generated by tool/generate_blank_card_poems.py; do not hand edit.\n'
                   '// Classical public-domain verse; sources and MIT notice are documented\n'
                   '// in docs/design/cat-scratch/poetry-library.md. Attribution is not shown.\n'
                   'const blankCardPoems = <String>[\n')
        content += ''.join("  '" + text.replace('\n', r'\n') + "',\n" for text in texts)
        content += '];\n'
        if args.check:
            if TARGET.read_text(encoding='utf-8') != content:
                raise ValueError('generated Dart catalog differs; regenerate it')
        else:
            TARGET.write_text(content, encoding='utf-8')
        if args.verbose:
            print(f'Source: {SOURCE}\nOutput: {TARGET}\nUTF-8 bytes: {len(content.encode())}')
        print('PASS poem library (2000 distinct couplets)')
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f'FAIL poem library: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
